In [12]:
from pathlib import Path
import joblib
import pandas as pd

In [14]:
# Get sample datasets
BASE_DIR = Path.cwd()

voyage_df = pd.DataFrame(
    joblib.load(BASE_DIR / "debug/6Db1zZcoO7JPczkjjU4vuX" / "songs.pkl")
)

velocity_df = pd.DataFrame(
    joblib.load(BASE_DIR / "debug/64wkinQzeyoBls7ES3RD6Z" / "songs.pkl")
)

In [15]:
# The voyage of 67 playlist
voyage_df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,track_youtube_id
0,1B2wrYVrPtd3CcrYwUwmPE,"Justin Bieber, Brandon Love, Chandler Moore",Freedom.,All She Wrote (feat. Brandon Love & Chandler M...,38,234400,False,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
1,7ciVByPgRrzDHnSuLiQ7Ju,"Audiomarc, Nasty C",Audio Czzle (feat. Nasty C),Audio Czzle (feat. Nasty C),34,274000,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
2,21vc2kQZMS00cAyNT82a1M,"¥$, Kanye West, Ty Dolla $ign, Bump J",VULTURES,VULTURES,1,237534,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
3,24lORMRGMv9sXpZJdN1PVm,"Dreezy, 6LACK, Kodak Black",Spar (feat. 6LACK & Kodak Black),Spar (feat. 6LACK & Kodak Black),44,231194,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
4,5hzrmJKIS2CHmvlUWkdlYy,Joyner Lucas,Seventeen,Seventeen,51,205925,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None

In [16]:
velocity_df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,track_youtube_id
0,1UyDQh3HBJwL6IxR9mXipZ,"DREAMDNVR, Boy In Space",AMNESIA (feat. Boy In Space),AMNESIA (feat. Boy In Space),47,175826,False,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
1,5SehvGGC53A7SZKCLXQcyt,Twenty One Pilots,Trench,Nico and the Niners,69,225040,False,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
2,2Fjz5ZC5BvFdCqcnTZ3ilH,Alan Walker,Sing Me to Sleep,Sing Me to Sleep,63,189333,False,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
3,1QgFLJ24l2fodb7SdGBVgy,Kujah,Broken Down,Broken Down,31,145058,False,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
4,6BRtWlr1VmsiPjIFnvg9Qv,Krewella,New World Pt. 1,Calm Down,43,190077,True,None,None,None,...,None,None,None,None,None,None,None,None,"edm, dubstep",None